---
- hosts: _ipserv_
  become: true
  tasks:
    - name: installation bind9
      apt: name=bind9 state=present

    - name: installation bind9utils
      apt: name=bind9utils state=present

    - name: demarre le service
      service: name=bind9 enabled=yes

