---
- hosts: _ipserv_
  become: true
  tasks:
    - name: installation dhcpd
      apt: name=isc-dhcp-server state=present

    - name: demarre le service
      service: name=isc-dhcp-server enabled=yes

